import Link from "next/link"
import style from './../styles.module.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ConferenceLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <nav className={style.subnavigation}>
        <Link href="/settings/profile" style={{ color: 'white', marginRight: 20 }}>Profile</Link> |
        <Link href="/settings/password" style={{ color: 'white', marginLeft: 20 }}>Password</Link>
      </nav>
      {children}
    </>
  )
}
